    
server:
  port: ${PORT:8100}

name: Git

message: Hello world Fuzail from YAML GIT

endpoints:
  health:
    sensitive: false
  shutdown:
    enabled: true
    
    
spring:
    data:
        mongodb:
            host: 192.168.99.100